// <auto-generated />
namespace InHouseApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StarRatingchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StarRatingchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202006020348304_StarRating change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
